/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fichas;

/**
 *
 * @author Admin
 */
public class TelaPersonagem extends javax.swing.JFrame {

    public int rolarD20() {
        return (int) (1 + Math.random() * 20);
    }

    public String sortearHabilidade() {
        String[] habilidades = {
            "Respiração Aquática",
            "Comunicação Marinha",
            "Bioluminescência",
            "Resistência à Pressão",
            "Natação Veloz"
        };

        int indice = (int) (Math.random() * habilidades.length);
        return habilidades[indice];
    }

    // Método 3: A fórmula matemática do poder
    public int calcularPoderGeral(int forca, int inteligencia, int carisma) {
        return (forca + inteligencia + carisma) / 3;
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPersonagem.class.getName());

    /**
     * Creates new form TelaPersonagem
     */
    public TelaPersonagem() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        comboArq = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btRolar = new javax.swing.JButton();
        btFicha = new javax.swing.JButton();
        txtResumo = new java.awt.TextArea();
        lblForca = new javax.swing.JLabel();
        lblInteligencia = new javax.swing.JLabel();
        lblCarisma = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Nome do personagem:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 27, -1, -1));

        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 24, 220, -1));

        comboArq.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        comboArq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Explorador", "Estrategista", "Inventor", "Artista", "Mago", "Sábio", "Rebelde" }));
        getContentPane().add(comboArq, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 96, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Arquétipo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 96, -1, -1));

        btRolar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btRolar.setText("Rolar atributos");
        btRolar.addActionListener(this::btRolarActionPerformed);
        getContentPane().add(btRolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 176, -1, -1));

        btFicha.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btFicha.setText("Gerar ficha");
        btFicha.addActionListener(this::btFichaActionPerformed);
        getContentPane().add(btFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 176, -1, -1));

        txtResumo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txtResumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 335, 604, 391));

        lblForca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblForca.setText("0");
        getContentPane().add(lblForca, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 273, -1, -1));

        lblInteligencia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblInteligencia.setText("0");
        getContentPane().add(lblInteligencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 273, -1, -1));

        lblCarisma.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCarisma.setText("0");
        getContentPane().add(lblCarisma, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 273, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("FORÇA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 273, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("INTELIGÊNCIA :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 273, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("CARISMA :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 273, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRolarActionPerformed
        // TODO add your handling code here:
        int forca = rolarD20();
        int inteligencia = rolarD20();
        int carisma = rolarD20();

        lblForca.setText(String.valueOf(forca));
        lblInteligencia.setText(String.valueOf(inteligencia));
        lblCarisma.setText(String.valueOf(carisma));
    }//GEN-LAST:event_btRolarActionPerformed

    private void btFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFichaActionPerformed
        // TODO add your handling code here:
        String nome = txtNome.getText();
    // Pega o item que foi selecionado na caixinha de opções
    String classe = comboArq.getSelectedItem().toString();

    // Pega os números que foram sorteados na tela e transforma de volta em Inteiro
    int f = Integer.parseInt(lblForca.getText());
    int i = Integer.parseInt(lblInteligencia.getText());
    int c = Integer.parseInt(lblCarisma.getText());

    // Usa as nossas engrenagens para calcular o resto
    int nivelPoder = calcularPoderGeral(f, i, c);
    String habilidadeSorteada = sortearHabilidade();

    // Monta o texto usando \n para pular as linhas na JTextArea
    String ficha = "========== FICHA DE PERSONAGEM ==========\n\n"
            + "Nome: " + nome + "\n"
            + "Arquétipo: " + classe + "\n\n"
            + "--- ATRIBUTOS ---\n"
            + "Força: " + f + "\n"
            + "Inteligência: " + i + "\n"
            + "Carisma: " + c + "\n\n"
            + "--- STATUS FINAL ---\n"
            + "Poder Geral: " + nivelPoder + "\n"
            + "Habilidade Única: " + habilidadeSorteada + "\n"
            + "=========================================";

    // Imprime na sua caixa branca!
    txtResumo.setText(ficha);
    }//GEN-LAST:event_btFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPersonagem().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFicha;
    private javax.swing.JButton btRolar;
    private javax.swing.JComboBox<String> comboArq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCarisma;
    private javax.swing.JLabel lblForca;
    private javax.swing.JLabel lblInteligencia;
    private javax.swing.JTextField txtNome;
    private java.awt.TextArea txtResumo;
    // End of variables declaration//GEN-END:variables
}
